# Find Support Vectors


In [1]:
# Load libraries
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
import numpy as np


In [2]:
#Load data with only two classes
iris = datasets.load_iris()
X = iris.data[:100,:]
y = iris.target[:100]


In [3]:

# Standarize features
scaler = StandardScaler()
X_std = scaler.fit_transform(X)


In [4]:
# Create support vector classifier object
svc = SVC(kernel='linear', random_state=0)

# Train classifier
model = svc.fit(X_std, y)


In [5]:
# View support vectors
model.support_vectors_


array([[-0.5810659 ,  0.42196824, -0.80497402, -0.50860702],
       [-1.52079513, -1.67737625, -1.08231219, -0.86427627],
       [-0.89430898, -1.4674418 ,  0.30437864,  0.38056609],
       [-0.5810659 , -1.25750735,  0.09637501,  0.55840072]])

In [6]:
# View indices of support vectors
model.support_


array([23, 41, 57, 98])

In [7]:
# View number of support vectors for each class
model.n_support_


array([2, 2])